version: '3'

services:
  # web:
  #   build:
  #     context: . 
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./:/var/www/html
  #   depends_on:
  #     - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/opt/mssql
    ports:
      - "1433:1433"
  
volumes:
  dbdata: {}